server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: cloud-consumer-order
