server:
  port: 7001
eureka:
  instance:
    hostname: peer1
  client:
    #不需要向注册中心注册
    register-with-eureka: false
    # 自己是注册中心， 不需要拉取注册信息
    fetch-registry: false
    service-url:
      # 与注册中心交互 查询服务与注册服务都要使用该地址
     defaultZone: http://peer2:${server.port}/eureka

